version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: covarege run -m unittest && coverage xml && coverage report -m
          

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
